In [2]:
from metaflow import Flow
flow = Flow('main_flow')
for run in flow:
    print(run)

Run('main_flow/2')
Run('main_flow/1')


In [ ]:
def list_all_vars_in_step(flow, step, run=None):
    """
    Lists all Metaflow artifacts in a particular flow in a particular step.

    Parameters:
    flow (String): Name of flow
    step (String): Name of step
    run (String): Number of run. Omit if you want the latest

    Returns:
    List of all artifacts stored in the step
    """

    

In [12]:
from metaflow import Step
latest_run = Flow('main_flow').latest_run
step = latest_run['train_model']
sample_train = step.task.data.sample_train
data = sample_train[0].numpy()
one_image = data[0,:,:,:]
print(one_image)
print(type(one_image))
print(one_image.shape)

[[[ 47.392517 114.83647   35.59838 ]
  [ 46.779472 114.37091   34.1453  ]
  [ 48.034855 115.084     34.207783]
  ...
  [ 46.63202   74.78806   43.39261 ]
  [  0.         0.         0.      ]
  [  0.         0.         0.      ]]

 [[ 52.41545  117.030624  40.017975]
  [ 52.178234 116.62718   38.658913]
  [ 52.806087 116.84942   38.340076]
  ...
  [ 37.899693  53.9925    39.225605]
  [  0.         0.         0.      ]
  [  0.         0.         0.      ]]

 [[ 56.74028  118.24907   43.830025]
  [ 56.957    118.202065  43.31298 ]
  [ 57.142372 118.20206   42.843224]
  ...
  [ 25.717606  33.291515  29.053535]
  [  0.         0.         0.      ]
  [  0.         0.         0.      ]]

 ...

 [[  0.         0.         0.      ]
  [  0.         0.         0.      ]
  [  0.         0.         0.      ]
  ...
  [  0.         0.         0.      ]
  [  0.         0.         0.      ]
  [  0.         0.         0.      ]]

 [[  0.         0.         0.      ]
  [  0.         0.         0.      ]


In [ ]:
import matplotlib as plt

# Display the image using matplotlib
plt.imshow(one_image)
plt.axis('off')  # Hide the axes
plt.show()